test_pod:
  enabled: false

loki:
  enabled: true
  isDefault: true

  serviceAccount:
    create: true
    name: loki
    annotations:
      eks.amazonaws.com/role-arn: ${iam_role_arn}

  config:
    auth_enabled: true

    server:
      http_listen_port: 3100

    common:
      path_prefix: /var/loki

    schema_config:
      configs:
        - from: 2024-01-01
          store: tsdb
          object_store: s3
          schema: v12
          index:
            prefix: loki_index_
            period: 24h

    storage_config:
      aws:
        s3: s3://${loki_bucket}
        region: ${aws_region}
        s3forcepathstyle: true

    compactor:
      working_directory: /var/loki/compactor
      shared_store: s3

    limits_config:
      enforce_metric_name: false
      max_entries_limit_per_query: 5000
      reject_old_samples: true
      reject_old_samples_max_age: 168h

promtail:
  enabled: true

  config:
    server:
      http_listen_port: 3101

    positions:
      filename: /run/promtail/positions.yaml

    clients:
      - url: ${loki_url}
        tenant_id: ${tenant_id}
        backoff_config:
          max_period: 5m
          max_retries: 10
          min_period: 500ms
        batchsize: 1048576
        batchwait: 1s
        timeout: 10s

    snippets:
      pipelineStages:
        - cri: {}
        - docker: {}

grafana:
  enabled: false

prometheus:
  enabled: false